In [1]:
import pandas as pd
football = pd.read_csv('C:\\Users\\vvoyt\\learning\\Skillfactory trainee\\Module B\\data\\data_sf.csv')
display(football.head())

,Unnamed: 0,Name,Age,Nationality,Club,Value,Wage,Position,Crossing,Finishing,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
0,0,L. Messi,31,Argentina,FC Barcelona,110500000,565000,RF,84,95,...,75,96,33,28,26,6,11,15,14,8
1,1,Cristiano Ronaldo,33,Portugal,Juventus,77000000,405000,ST,84,94,...,85,95,28,31,23,7,11,15,14,11
2,2,Neymar Jr,26,Brazil,Paris Saint-Germain,118500000,290000,LW,79,87,...,81,94,27,24,33,9,9,15,15,11
3,3,De Gea,27,Spain,Manchester United,72000000,260000,GK,17,13,...,40,68,15,21,13,90,85,87,88,94
4,4,K. De Bruyne,27,Belgium,Manchester City,102000000,355000,RCM,93,82,...,79,88,68,58,51,15,13,5,10,13

In [20]:
display(football.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12897 entries, 0 to 12896
Data columns (total 42 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Unnamed: 0       12897 non-null  int64
 1   Name             12897 non-null  object
 2   Age              12897 non-null  int64
 3   Nationality      12897 non-null  object
 4   Club             12897 non-null  object
 5   Value            12897 non-null  int64
 6   Wage             12897 non-null  int64
 7   Position         12897 non-null  object
 8   Crossing         12897 non-null  int64
 9   Finishing        12897 non-null  int64
 10  HeadingAccuracy  12897 non-null  int64
 11  ShortPassing     12897 non-null  int64
 12  Volleys          12897 non-null  int64
 13  Dribbling        12897 non-null  int64
 14  Curve            12897 non-null  int64
 15  FKAccuracy       12897 non-null  int64
 16  LongPassing      12897 non-null  int64
 17  BallControl      12897 non-null  int64
 18  Acceleration     12897 non-null  int64
 19  SprintSpeed      12897 non-null  int64
 20  Agility          12897 non-null  int64
 21  Reactions        12897 non-null  int64
 22  Balance          12897 non-null  int64
 23  ShotPower        12897 non-null  int64
 24  Jumping          12897 non-null  int64
 25  Stamina          12897 non-null  int64
 26  Strength         12897 non-null  int64
 27  LongShots        12897 non-null  int64
 28  Aggression       12897 non-null  int64
 29  Interceptions    12897 non-null  int64
 30  Positioning      12897 non-null  int64
 31  Vision           12897 non-null  int64
 32  Penalties        12897 non-null  int64
 33  Composure        12897 non-null  int64
 34  Marking          12897 non-null  int64
 35  StandingTackle   12897 non-null  int64
 36  SlidingTackle    12897 non-null  int64
 37  GKDiving         12897 non-null  int64
 38  GKHandling       12897 non-null  int64
 39  GKKicking        12897 non-null  int64
 40  GKPositioning    12897 non-null  int64
 41  GKReflexes       12897 non-null  int64
dtypes: int64(38), object(4)
memory usage: 4.1+ MB

None

In [3]:
display(football.describe())

,Unnamed: 0,Age,Value,Wage,Crossing,Finishing,HeadingAccuracy,ShortPassing,Volleys,Dribbling,...,Penalties,Composure,Marking,StandingTackle,SlidingTackle,GKDiving,GKHandling,GKKicking,GKPositioning,GKReflexes
count,12897.000000,12897.000000,1.289700e+04,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,...,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000,12897.000000
mean,6605.040862,24.795379,2.112449e+06,7517.562224,47.076374,42.876328,50.202528,56.026983,40.295030,52.461735,...,46.459874,55.942932,45.655811,46.186710,44.386679,17.218345,16.962317,16.797938,16.950221,17.315965
std,3782.545526,4.872212,6.498424e+06,23061.985387,18.043470,19.096935,17.281593,14.740436,17.080687,18.871643,...,15.479313,11.280631,19.456346,21.172586,20.726546,18.085618,17.349624,16.971411,17.369297,18.335817
min,0.000000,16.000000,0.000000e+00,1000.000000,5.000000,2.000000,4.000000,7.000000,4.000000,4.000000,...,5.000000,12.000000,3.000000,2.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,3357.000000,21.000000,2.500000e+05,1000.000000,35.000000,28.000000,43.000000,50.000000,28.000000,45.000000,...,37.000000,49.000000,29.000000,25.000000,23.000000,8.000000,8.000000,8.000000,8.000000,8.000000
50%,6622.000000,24.000000,5.000000e+05,2000.000000,51.000000,45.000000,54.000000,60.000000,41.000000,58.000000,...,47.000000,56.000000,51.000000,54.000000,51.000000,11.000000,11.000000,11.000000,11.000000,11.000000
75%,9876.000000,28.000000,8.500000e+05,4000.000000,61.000000,59.000000,62.000000,65.000000,53.000000,65.000000,...,58.000000,63.000000,62.000000,64.000000,62.000000,14.000000,14.000000,14.000000,14.000000,14.000000
max,13125.000000,45.000000,1.185000e+08,565000.000000,93.000000,95.000000,94.000000,93.000000,90.000000,97.000000,...,91.000000,96.000000,93.000000,93.000000,91.000000,90.000000,92.000000,91.000000,90.000000,94.000000

In [4]:
display(football.describe(include = ['object']))

                Name Nationality             Club Position
count          12897       12897            12897    12897
unique         12326         156              650       27
top     J. Rodríguez     England  Shonan Bellmare       GK
freq               9        1368               30     1641

In [23]:
#1.8.1
#Чему равен средний возраст (Age), футболистов в наборе данных, округлённый до целого?
print('Age: ', football.Age.mean())

#Каково количество непустых строк в колонке Composure (Хладнокровие) набора данных о футболистах?
print('Composure: ', football.Composure.count())

#Каково в наборе данных о футболистах стандартное отклонение параметра коротких пасов (ShortPassing), округлённое до второго знака после запятой?
print('ShortPassing: ', football.ShortPassing.std())

#Какова сумма заработных плат за год (Wage) в наборе данных о футболистах?
print('Wage: ', football.Wage.sum())

#Какова минимальная стоимость футболиста?
print('Value: ', football.Value.min())

Age:  24.795378770256647
Composure:  12897
ShortPassing:  14.740435689517149
Wage:  96954000
Value:  0

In [6]:
# 1.9.1
#Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых выше среднего? Ответ округлите до сотых.
print('#1.9.1: ', "{:.2f}".format(football[football.Wage > football.Wage.mean()].SprintSpeed.mean()))

#1.9.1:  67.57

In [7]:
#1.9.2
#Какова средняя скорость (SprintSpeed) футболистов, зарплата (Wage) которых ниже среднего? Ответ округлите до сотых.
print('#1.9.2: ', "{:.2f}".format(football[football.Wage < football.Wage.mean()].SprintSpeed.mean()))

#1.9.2:  62.41

In [8]:
#1.9.3
#Какую позицию (Position) занимает футболист с самой высокой зарплатой (Wage)?
print('#1.9.3: ', football[football.Wage == football.Wage.max()].Position.max())

#1.9.3:  RF

In [9]:
#1.9.4
#Сколько пенальти (Penalties) забили бразильские (Nationality, Brazil) футболисты за период,
    #данные о котором представлены в датасете?
print('#1.9.4: ', football[football.Nationality == 'Brazil'].Penalties.sum())

#1.9.4:  22789

In [10]:
#1.9.5
#Укажите средний возраст (Age) игроков, у которых точность удара головой (HeadingAccuracy) > 50. Ответ округлите до сотых.
print('#1.9.5: ', "{:.2f}".format(football[football.HeadingAccuracy > 50].Age.mean()))

#1.9.5:  25.59

In [11]:
#1.9.6
#Укажите возраст (Age) самого молодого игрока, у которого хладнокровие (Composure)
    #и реакция (Reactions) превышают 90% от максимального значения, представленного в датасете.
print('#1.9.6: ', football[(football.Composure > football.Composure.max()*0.9) 
                           & (football.Reactions > football.Reactions.max()*0.9) ].Age.min())

#1.9.6:  24

In [12]:
#1.9.7
#Определите, на сколько средняя реакция (Reactions) самых взрослых игроков (т.е. игроков, чей возраст (Age)
    #равен максимальному) больше средней реакции самых молодых игроков. Ответ округлите до сотых.
print('#1.9.7: ', "{:.2f}".format(football[football.Age == football.Age.max()].Reactions.mean() 
                          - football[football.Age == football.Age.min()].Reactions.mean()))

#1.9.7:  22.64

In [13]:
#1.9.8
#Из какой страны (Nationality) происходит больше всего игроков, чья стоимость (Value) превышает среднее значение?
            ##print('#1.9.8: ', football[football.Value > football.Value.mean()].Nationality.min())
ForNationality = football[(football.Value > football.Value.mean())]
NationalityCount = ForNationality['Nationality'].value_counts()
print('#1.9.8: ', NationalityCount.index[0])

#1.9.8:  Spain

In [14]:
#1.9.9
#Во сколько раз средняя зарплата (Wage) голкипера (Position, GK) с максимальным значением показателя
    #«Рефлексы» (GKReflexes) выше средней зарплаты голкипера с максимальным значением
    #показателя «Владение мячом» (GKHandling)? Ответ округлите до сотых.
AvgGKWage1 = football[(football.Position == 'GK')&
        (football.GKReflexes == football.GKReflexes.max())].Wage.mean()
AvgGKWage2 = football[(football.Position == 'GK')&
        (football.GKHandling == football.GKHandling.max())].Wage.mean()
print('#1.9.9: ', "{:.2f}".format(AvgGKWage1/AvgGKWage2))

#1.9.9:  2.77

In [15]:
#1.9.10
#Во сколько раз средняя сила удара (ShotPower) самых агрессивных игроков (игроков с максимальным значением
    #показателя «Агрессивность» (Aggression)) выше силы удара игроков с минимальной агрессией? Ответ округлите до сотых.
MaxAggression = football[(football.Aggression == football.Aggression.max())].ShotPower.mean()
MinAggression = football[(football.Aggression == football.Aggression.min())].ShotPower.mean()
print('#1.9.10: ', "{:.2f}".format(MaxAggression/MinAggression))

#1.9.10:  2.08